# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Surface Calculator', kernelModule='surfacecal', kernelFunction='surfacecal', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgSeparator(p='DialogBox')
RsgTextField(p='DialogBox', fieldType='String', ncols=60, labelText='File name              ', keyword='name', default='2018_oct_08_05')
RsgTextField(p='DialogBox', fieldType='String', ncols=60, labelText='Working directory: ', keyword='workdir', default='/home/efm/work17/small_plate_explicit/')
RsgTextField(p='DialogBox', fieldType='String', ncols=60, labelText='File directory: ', keyword='odbpath', default='/home/efm/work17/small_plate_explicit/kb_chapter/')
RsgCheckButton(p='DialogBox', text='Amplitude comparison', keyword='ampcomp', default=True)
RsgTextField(p='DialogBox', fieldType='String', ncols=60, labelText='File to compare with             ', keyword='namecomp', default='2018_oct_08_06')
RsgSeparator(p='DialogBox')
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Type of signal:                    ', keyword='signaltype', default='Single frequency excitation (SFE)', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_1', text='Single frequency excitation (SFE)')
RsgListItem(p='ComboBox_1', text='Vibro acoustic modulation (VAM)')
RsgListItem(p='ComboBox_1', text='Sweep signal excitation (SWP)')
RsgListItem(p='ComboBox_1', text='Amplitude modulated SFE (ASFE)')
RsgTabBook(name='TabBook_2', p='DialogBox', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgTabItem(name='TabItem_3', p='TabBook_2', text='SFE')
RsgTextField(p='TabItem_3', fieldType='Float', ncols=12, labelText='Frequency (kHz):', keyword='f0sfe', default='25.404')
RsgTextField(p='TabItem_3', fieldType='Integer', ncols=12, labelText='Resolution:         ', keyword='n0sfe', default='24')
RsgTextField(p='TabItem_3', fieldType='Integer', ncols=12, labelText='Periods to skip:         ', keyword='N0skipsfe', default='18')
RsgTabItem(name='TabItem_4', p='TabBook_2', text='VAM')
RsgGroupBox(name='GroupBox_1', p='TabItem_4', text='Pump frequency', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Frequency (kHz):', keyword='f0vam', default='5')
RsgGroupBox(name='GroupBox_3', p='TabItem_4', text='Probe frequency', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Frequency (kHz):', keyword='f1vam', default='100')
RsgTextField(p='GroupBox_3', fieldType='Integer', ncols=12, labelText='Resolution:         ', keyword='n0vam', default='24')
RsgTabItem(name='TabItem_5', p='TabBook_2', text='SWP')
RsgTextField(p='TabItem_5', fieldType='Float', ncols=12, labelText='Start frequency (kHz):', keyword='f0swp', default='30')
RsgTextField(p='TabItem_5', fieldType='Float', ncols=12, labelText='End frequency (kHz):  ', keyword='f1swp', default='40')
RsgTextField(p='TabItem_5', fieldType='Integer', ncols=12, labelText='Resolution:                 ', keyword='n0swp', default='12')
RsgTabItem(name='TabItem_6', p='TabBook_2', text='ASFE')
RsgSeparator(p='TabItem_6')
RsgTextField(p='TabItem_6', fieldType='Float', ncols=12, labelText='Frequency (kHz):  ', keyword='f0asfe', default='25')
RsgTextField(p='TabItem_6', fieldType='Float', ncols=12, labelText='Resolution:         ', keyword='n0asfe', default='32')
RsgSeparator(p='DialogBox')
dialogBox.show()
