# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Point Calculator', kernelModule='pointcal', kernelFunction='pointcal', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgPickButton(p='DialogBox', text='Select node for calculations:', keyword='node0', prompt='Node', entitiesToPick='ODB_ALL|NODES', numberToPick='ONE')
RsgSeparator(p='DialogBox')
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Type of signal:      ', keyword='signaltype', default='Single frequency excitation (SFE)', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_1', text='Single frequency excitation (SFE)')
RsgListItem(p='ComboBox_1', text='Vibro acoustic modulation (VAM)')
RsgListItem(p='ComboBox_1', text='Sweep signal excitation (SWP)')
RsgListItem(p='ComboBox_1', text='Amplitude modulated SFE (ASFE)')
RsgLabel(p='DialogBox', text='Select the tab corresponding to your selection above', useBoldFont=False)
RsgTabBook(name='TabBook_2', p='DialogBox', layout='LAYOUT_FILL_X')
RsgTabItem(name='TabItem_3', p='TabBook_2', text='SFE')
RsgSeparator(p='TabItem_3')
RsgTextField(p='TabItem_3', fieldType='Float', ncols=12, labelText='Frequency (kHz):', keyword='f0sfe', default='25.404')
RsgTextField(p='TabItem_3', fieldType='Integer', ncols=12, labelText='Resolution:         ', keyword='n0sfe', default='12')
RsgTextField(p='TabItem_3', fieldType='Integer', ncols=12, labelText='Periods to skip:         ', keyword='N0skipsfe', default='5')
RsgTabItem(name='TabItem_4', p='TabBook_2', text='VAM')
RsgSeparator(p='TabItem_4')
RsgGroupBox(name='GroupBox_1', p='TabItem_4', text='Pump frequency', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Frequency (kHz):', keyword='f0vam', default='5')
RsgGroupBox(name='GroupBox_3', p='TabItem_4', text='Probe frequency', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Frequency (kHz):', keyword='f1vam', default='100')
RsgTextField(p='GroupBox_3', fieldType='Integer', ncols=12, labelText='Resolution:         ', keyword='n0vam', default='24')
RsgTextField(p='GroupBox_3', fieldType='Integer', ncols=12, labelText='Periods to skip:         ', keyword='N0skipvam', default='5')
RsgTabItem(name='TabItem_5', p='TabBook_2', text='SWP')
RsgTextField(p='TabItem_5', fieldType='Float', ncols=12, labelText='Start frequency (kHz):', keyword='f0swp', default='20')
RsgTextField(p='TabItem_5', fieldType='Float', ncols=12, labelText='End frequency (kHz):  ', keyword='f1swp', default='30')
RsgTextField(p='TabItem_5', fieldType='Integer', ncols=12, labelText='Resolution:                 ', keyword='n0swp', default='24')
RsgTabItem(name='TabItem_6', p='TabBook_2', text='ASFE')
RsgSeparator(p='TabItem_6')
RsgTextField(p='TabItem_6', fieldType='Float', ncols=12, labelText='Frequency (kHz):  ', keyword='f0asfe', default='25')
RsgTextField(p='TabItem_6', fieldType='Float', ncols=12, labelText='Resolution:         ', keyword='n0asfe', default='32')
RsgSeparator(p='DialogBox')
dialogBox.show()
